version: '3.8'
services:
  db:
    image: postgres:13
    container_name: bharatfoodtrace_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bharatfoodtrace
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
